# main menu
[[main]]
name = "About"
url = "about/"
weight = 1

[[main]]
name = "FIRE Calculators"
hasChildren = true
weight = 2

  [[main]]
  parent = "FIRE Calculators"
  name = "CoastFIRE Calculator"
  url = "calculators/coast/"
  weight = 1

  [[main]]
  parent = "FIRE Calculators"
  name = "Safe Withdrawal Rate"
  url = "calculators/swr/"
  weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "FIRE Calculators"
url = "calculators/"
weight = 2

[[footer]]
name = "Blog"
url = "blog/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4
