# main menu
[[main]]
name = "Blog"
url = "blog/"
weight = 1

[[main]]
name = "FIRE Calculators"
hasChildren = true
weight = 2

  [[main]]
  parent = "FIRE Calculators"
  name = "CoastFIRE Calculator"
  url = "calculators/coast/"
  weight = 1

  [[main]]
  parent = "FIRE Calculators"
  name = "Safe Withdrawal Rate"
  url = "calculators/swr/"
  weight = 2

[[main]]
name = "Data Policy"
url = "terms-and-conditions/"
weight = 3

# footer menu
[[footer]]
name = "FIRE Calculators"
url = "calculators/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Data Policy"
url = "terms-and-conditions/"
weight = 3
