# main menu
[[main]]
name = "Blog"
url = "blog/"
weight = 1

[[main]]
name = "FIRE Calculators"
hasChildren = true
weight = 2

  [[main]]
  parent = "FIRE Calculators"
  name = "FIRE Calculator"
  url = "calculators/fire/"
  weight = 2

[[main]]
name = "Data Policy"
url = "terms-and-conditions/"
weight = 3

# footer menu
[[footer]]
name = "FIRE Calculators"
url = "calculators/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Data Policy"
url = "terms-and-conditions/"
weight = 3
