#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "FirePlace"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "We tell cool stories with data and make tools so you can build wealth confidently."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "Made in Austin, Texas."

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script= ""

# buy premium popup
buy_premium_popup = false

# Main Sections
mainSections= ["blog"]

# contact information
[contact_info]
address = "Austin, Texas"
phone = [""]
email = ["info@fireplace.cash"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "Newsletter"
link = "https://gethugothemes.com/products/andromeda/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = false
title = "Sign Up for the Newsletter Now"
content = "Don't worry. We only use your email to send updates on when new content is available."
button = "Sign Up"
button_link = "https://gethugothemes.com/products/andromeda/"

############################# social site ########################
# [[social]]
# title = "Andromeda"
# icon = "lab la-facebook-f" # https://icons8.com/line-awesome
# link = "#!"
#
# [[social]]
# title = "AndromedaTweet"
# icon = "lab la-twitter" # https://icons8.com/line-awesome
# link = "#!"
#
# [[social]]
# title = "AndromedaIn"
# icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
# link = "#!"
#
# [[social]]
# title = "AndromedaPin"
# icon = "lab la-pinterest" # https://icons8.com/line-awesome
# link = "#!"
